spring:
  application:
    name: optivolt-core
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/optivolt_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgrespassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: optivolt-core-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

ignite:
  client-mode: ${IGNITE_CLIENT_MODE:true}
  peer-class-loading-enabled: true
  addresses: ${IGNITE_ADDRESSES:localhost:47500..47509}

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
